### ISSUE TITLE
CurseForge2Discord won't post any messages

### ISSUE THREAD

**Issue by Griefed** [ijo42/CurseForge2Discord#5]
Hello ijo42,

I've been trying to get your fork of ErdbeerbaerLP's bot to work, however, I'm having trouble getting your version to post anything at all. I'm wondering whether I've misconfigured it, maybe.

```
ver = 5

ids = [
    # Uplink
    "430517;;ID of the Channel to post to;;The part of the wehook url after the last /",
    "243121;;ID of the Channel to post to;;The part of the wehook url after the last /;;ID of a role",
    "239197;;ID of the Channel to post to;;The part of the wehook url after the last /;;ID of a role"
]

changelogDiscordFormat = "md"

messageDescription = "New File(s) Detected For CurseForge Project(s)"

updateFileLink="curse"

mentionRole=ID of a role

footerImage="direkt link to a .png file"
```

The cache written by your bot looks like this:
```
CraftTweaker;;3178869
Survive Create Prosper 4;;3177935
Quark;;3177615
```

So the bot is detecting projects and files just fine as far as I can tell, however, it's not posting any messages at all. The Webhook was created for the same channel as the ID I've entered in the "ids" section of the config.

Any help would be appreciated. Thanks!

Cheers,
Griefed

**Comment by ijo42** [comment]
Hello!
Thank you for your interest in my little project
It is important to understand that when the bot first loads, it caches all the projects, but does not announce them, it says yes, this one was before I turned it on. The bot will send the first message when it catches a new file on any of the projects

I haven't written any documents about the new configurations, but a configuration comment might help.
`"projectId;;channelId;;webhookToken;;RoleID"`
may be `435552;;$1:$2`
Where placeholders get's from **Webhook URL**
discord.com/api/webhooks/**61294...**/**J2NM0S...**

What is important, the channel ID and the channel ID from the WebHook do not match
I may not be fully aware of this mechanics, but the values are used exclusively from the WebHook URL

**Comment by Griefed** [comment]
So the Channel ID from the webhook must be the same as used for channelID, gotcha. Thanks!

**Comment by ijo42** [comment]
You're welcome!
