### ISSUE TITLE
Getting "Failed to execute request:" in logs

### ISSUE THREAD

**Issue by Griefed** [ijo42/CurseForge2Discord#8]
I've configured four projects in the bot.conf and all four of them are generating `Failed to execute request:" in the logs:

> Failed to execute request: Request{method=GET, url=https://addons-ecs.forgesvc.net/api/v2/addon/430517, tags={class retrofit2.Invocation=com.therandomlabs.curseapi.forgesvc.ForgeSvc.getProject() [430517]}}
Failed to execute request: Request{method=GET, url=https://addons-ecs.forgesvc.net/api/v2/addon/378473, tags={class retrofit2.Invocation=com.therandomlabs.curseapi.forgesvc.ForgeSvc.getProject() [378473]}}
Failed to execute request: Request{method=GET, url=https://addons-ecs.forgesvc.net/api/v2/addon/438915, tags={class retrofit2.Invocation=com.therandomlabs.curseapi.forgesvc.ForgeSvc.getProject() [438915]}}
Failed to execute request: Request{method=GET, url=https://addons-ecs.forgesvc.net/api/v2/addon/378719, tags={class retrofit2.Invocation=com.therandomlabs.curseapi.forgesvc.ForgeSvc.getProject() [378719]}}

My bot.conf (redacted roles/channel ids/tokens because duh):
```
# Don´t change this! Used internally to backup and reset the config if needed!
ver = 5

# Provide some CurseForge project IDs you want the bot to listen to
#
# Role ID doesn't have to be set, if its not don't include second ;;
# NOTE: Role ID can only be set if a channel id is set as well
# NOTE 2: channelId must me grabbed from DISCORD WEBHOOK
# e.g. https://discord.com/api/webhooks/xxx/zzzz
# which xxx is channel id, zzzz is webhook token
ids = [
    "430517;;channel_id;;webhook_token",
    "378473;;channel_id;;webhook_token",
    "438915;;channel_id;;webhook_token",
    "378719;;channel_id;;webhook_token"
]

## UPDATE MESSAGE OPTIONS ##
# Provide a language syntax name to have the changelog formatted inside the embedded message for easier viewing if desired.
#
# Can be very useful if project owner/author uses discord Markdown formatting in their changelog
# Uploads as plain text if not changed (example: yml, md, css) Only choose one syntax
changelogDiscordFormat = "md"

# This sets the text that appears as the message description in the update notification
# (the text directly under the project name which is the message title)
#
# This can adhere to discord markdown rules but due to how the message is formatted as a whole, keep this
# message under 250 characters
messageDescription = "New File(s) Detected For CurseForge Project(s)"

# Sets the message to include a download link for the new project file
#
# Use the following 3 options only to set the link
# "direct" = Direct link to download the file
# "curse" = Link to the file download page on curseforge.com
# "nolink" = Do not include a download link
updateFileLink = "CURSE"

# If you want the message to mention a particular role when a update message is sent, add the Role ID here
#
# You may provide custom image by URL into Message Footer
mentionRole = role_id

footerImage = "FOOTER_URL"
```

Any idea what is happening here?

**Comment by ijo42** [comment]
Hello, Yes, I am aware of this information. It is not possible to collect information about the project status on the exchange rate from the container. And only from the container, the launch on the host machine works successfully
I am indignant about the fact that this version is in the release.
I have a few ideas about what this might be about. Perhaps the wrong configuration of s6 / its startup scripts or I somehow broke the functionality of network-bridge. IDK. long hours of debug did not give the proper result, I am at a dead end

I do not recommend using the latest version

**Comment by Griefed** [comment]
Alrighty, thanks for the information. 🙂 Take it easy, don't stress yourself.

**Comment by ijo42** [comment]
apparently, the error lies in the custom JDK environment, which is collected using jlink. My theory is that retrofit 2 depends on some java module that I don't install in the image. after several hours of searching, I could not determine which module is needed.

A temporary solution is to build an image w/ '--build-arg LIBERICA_IMAGE_VARIANT=lite'. The image will be much larger, but it will be working

**Comment by Griefed** [comment]
Thank you for getting back on this. :) I'll go ahead and close this ticket now. Stay safe!
